@startuml

title __PIECE's Class Diagram__\n

  namespace fr.rphstudio.chess.game {
    namespace piece {
      class fr.rphstudio.chess.game.piece.BishopMove {
          + getMove()
      }
    }
  }
  

  namespace fr.rphstudio.chess.game {
    namespace piece {
      class fr.rphstudio.chess.game.piece.KingMove {
          + checkLongCastle()
          + checkShortCastle()
          + getMove()
      }
    }
  }
  

  namespace fr.rphstudio.chess.game {
    namespace piece {
      class fr.rphstudio.chess.game.piece.KnightMove {
          + getMove()
      }
    }
  }
  

  namespace fr.rphstudio.chess.game {
    namespace piece {
      class fr.rphstudio.chess.game.piece.PawnMove {
          + getMove()
      }
    }
  }
  

  namespace fr.rphstudio.chess.game {
    namespace piece {
      class fr.rphstudio.chess.game.piece.QueenMove {
          + getMove()
      }
    }
  }
  

  namespace fr.rphstudio.chess.game {
    namespace piece {
      class fr.rphstudio.chess.game.piece.RookMove {
          + getMove()
      }
    }
  }
  

  fr.rphstudio.chess.game.piece.BishopMove .up.|> fr.rphstudio.chess.interf.IMove
  fr.rphstudio.chess.game.piece.KingMove .up.|> fr.rphstudio.chess.interf.IMove
  fr.rphstudio.chess.game.piece.KnightMove .up.|> fr.rphstudio.chess.interf.IMove
  fr.rphstudio.chess.game.piece.PawnMove .up.|> fr.rphstudio.chess.interf.IMove
  fr.rphstudio.chess.game.piece.QueenMove .up.|> fr.rphstudio.chess.interf.IMove
  fr.rphstudio.chess.game.piece.RookMove .up.|> fr.rphstudio.chess.interf.IMove


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
